---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: metis-ii
description: An atomic distro for an audience of one (me). Based on BlueBuild.

base-image: ghcr.io/ublue-os/kinoite-main
image-version: latest

modules:
  # ————————————————————————————————————————————————
  #  ··· Branding
  #      + replace Fedora logos with generic logos
  #      + apply "Metis II" branding
  #      + regenerate initramfs to display generic logos on boot screen
  - type: script
    # Using the manual dnf command here since BlueBuild's `dnf` module doesn't support package
    # swapping, and doing a two-step install/remove will also nuke the KDE Plasma desktop.
    snippets: ["dnf swap fedora-logos generic-logos -y"]
  - type: os-release
    properties:
      ID: metis-ii
      ID_LIKE: fedora
      NAME: Metis II
      PRETTY_NAME: Metis II (based on Fedora Kinoite)
      HOME_URL: https://github.com/jahinzee/metis-ii
      DOCUMENTATION_URL: https://github.com/jahinzee/metis-ii/blob/main/README.md
      SUPPORT_URL: https://github.com/jahinzee/metis-ii/issues
      BUG_REPORT_URL: https://github.com/jahinzee/metis-ii/issues
  - type: initramfs

  # ————————————————————————————————————————————————
  #  ··· Packages: KDE Applications
  #      + install KDE utilities for multimedia and system maintenance
  - type: dnf
    repos:
      cleanup: true
      # [EXT;COPR]
      copr: [matinlotfali/KDE-Rounded-Corners]
    install:
      packages:
        - elisa
        - falkon
        - gwenview
        - haruna
        - kalk
        - kclock
        - kcm_systemd
        - kcolorchooser
        - kolourpaint
        - krdc
        - kwin-effect-roundcorners
        - merkuro
        - okular
        - plasma-browser-integration
        - yakuake

  # ————————————————————————————————————————————————
  #  ··· Packages: CLI utilities
  #      + install cli tweaks and utilities
  - type: dnf
    repos:
      cleanup: true
      copr:
        # [EXT;COPR]
        - atim/starship
        # [EXT;COPR]
        - dturner/eza
        # [EXT;COPR]
        - lilay/topgrade
    install:
      packages:
        - bat
        - btop
        - fastfetch
        - fd
        - fish
        - helix
        - pipx
        - qalculate
        - ripgrep
        - starship
        - topgrade
        - vim
        - zoxide

  # ————————————————————————————————————————————————
  #  ··· Homebrew
  #      + install Homebrew
  - type: brew
    nofile-limits: true
    brew-analytics: false

  # ————————————————————————————————————————————————
  #  ··· Packages: Virtualisation
  #      + install the libvirt/QEMU/KVM virtualisation stack
  - type: dnf
    group-install:
      packages: [virtualization]

  # ————————————————————————————————————————————————
  #  ··· Packages: IMEs
  #      + install IMEs for Japanese (fcitx) and Bengali (openbangla)
  - type: dnf
    repos:
      cleanup: true
      # [EXT;COPR]
      copr: [badshah/openbangla-keyboard]
    install:
      packages:
        - fcitx5-mozc
        - fcitx-openbangla

  # ————————————————————————————————————————————————
  #  ··· Packages: Printer drivers
  #      + install Brother laser printer drivers
  - type: dnf
    install:
      packages: [printer-driver-brlaser]

  # ————————————————————————————————————————————————
  #  ··· Ghostty
  #      + install Ghostty
  - type: dnf
    repos:
      cleanup: true
      # [EXT;COPR]
      copr: [scottames/ghostty]
    install:
      packages: [ghostty]

  # ————————————————————————————————————————————————
  #  ··· Packages: Syncthing
  #      + install Syncthing and Syncthing-Tray and KDE integrations (Plasmoid, KIO and CLI)
  - type: dnf
    repos:
      files:
        # [EXT;OBS]
        - https://download.opensuse.org/repositories/home:/mkittler:/vcs/Fedora_%OS_VERSION%/home:mkittler:vcs.repo
    install:
      packages:
        - syncthing
        - syncthingctl-qt6
        - syncthingfileitemaction-qt6
        - syncthingplasmoid-qt6

  # ————————————————————————————————————————————————
  #  ··· Packages: Zen Browser
  #      + install Zen Browser with /opt fixes
  - type: dnf
    repos:
      cleanup: true
      # [EXT;COPR]
      copr: [sneexy/zen-browser]
    optfix: [zen]
    install:
      packages: [zen-browser]

  - type: signing

  # ————————————————————————————————————————————————
  #  ··· Extern: KAdwSettings
  #      + install KAdwSettings (manually) and through dependencies
  - type: script
    scripts: [install-kadwsettings.sh]
